name: research
channels:
  - conda-forge
  - nvidia # nvidia channel for cuda packages
  # We want to have a reproducible setup, so we don't want default channels,
  # which may be different for different users. All required channels should
  # be listed explicitly here.
  - nodefaults
dependencies:
  - python=3.10

  # ML libraries
  - pytorch::pytorch>=2.0
  - pytorch::pytorch-cuda=12.1 # [linux]
  - torchvision
  - timm
  - wandb
  - datasets
  - huggingface_hub
  - safetensors

  # Scientific stack
  - numpy
  - pandas
  - scikit-learn
  - matplotlib
  - seaborn
  - pillow
  - tqdm

  # Dev dependencies (configured in pyproject.toml)
  - black
  - ruff
  - isort
  - mypy
  - pytest

  # pip dependencies
  - pip
  - pip:
      - opencv-python-headless
      # These pins take precedence over the conda pytorch packages above and
      # determine the torch/torchvision versions in the final environment.
      - torch>=2.3.1
      - torchvision>=0.18.1

# Non-standard section listing target platforms for conda-lock:
platforms:
  - linux-64
